### ISSUE TITLE
Got error:  'NoneType' object has no attribute 'input'

### ISSUE THREAD

**Issue by hungkien05** [m-primo/Facebook-Brute-Force#3]
I got this error every time I ran the script

`2021/12/24 11:24:15 PM INFO: [*] Attempt #1 with user: 'x@x.com' and password: 'mypassword'.`
`2021/12/24 11:24:15 PM INFO: [!] Caught an Exception: 'NoneType' object has no attribute 'input'`
`2021/12/24 11:24:15 PM INFO: [-] No Password was Found. `

**Comment by hungkien05** [comment]
I also sometimes encountered this error too:

```[*] Processing...
[*] Attempt #1 with user: '0981058354' and password: 'Nhattan124'.
[!] Caught an Exception: HTTPSConnectionPool(host='mbasic.facebook.com', port=443): Read timed out. (read timeout=2)
[-] No Password was Found.```

**Comment by hungkien05** [comment]
I also sometimes encounter this error too:
```[*] Processing...
[*] Attempt #1 with user: 'x@x.com' and password: 'mypassword'.
[!] Caught an Exception: HTTPSConnectionPool(host='mbasic.facebook.com', port=443): Read timed out. (read timeout=2)
[-] No Password was Found.```

**Comment by m-primo** [comment]
Hello @hungkien05, thank you for submitting an issue.
1. The first error sometimes will show when an input name called `lsd` does not exist in the Facebook login form. I don't know what really happened in this case, but when I investigated it the first time this showed to me, I found sometimes Facebook blocks the login for that account for a couple of seconds. So, in this case, there's nothing we can do about it, because it's from Facebook side, not the script.
2. The second error is the timeout (current is 2 seconds), the request will timeout after this seconds. You can edit the timeout seconds in the variable `DEFAULT_TIMEOUT`.

**Comment by hungkien05** [comment]
About the first error, you mean that I should try after some times right ?

**Comment by m-primo** [comment]
Yes, and also if you have so many passwords, it'll work correctly for about 99% of the passwords.
I tried this method many times.
